type OpenSourceList=readonly{name:string,url:string}[]
export const OpenSourceList:OpenSourceList=[
    {
        name:"electron",
        url:"https://github.com/electron/electron",
    },
    {
        name:"react",
        url:"https://github.com/facebook/react",
    },
    {
        name:"react-router",
        url:"https://github.com/remix-run/react-router"
    },
    {
        name:"vite",
        url:"https://github.com/vitejs/vite",
    },
    {
        name:"ws",
        url:"https://github.com/websockets/ws"
    },
    {
        name:"crypto-random-string",
        url:"://github.com/sindresorhus/crypto-random-string",
    },
    {
        name:"dexie",
        url:"https://github.com/dexie/Dexie.js"
    },
    {
        name:"dexie-react-hooks",
        url:"https://github.com/dexie/Dexie.js"
    },
    {
        name:"fs-extra",
        url:"https://github.com/jprichardson/node-fs-extra"
    },
    {
        name:"get-proxy-settings",
        url:"https://github.com/Azure/get-proxy-settings"
    },
    {
        name:"js-sha256",
        url:"https://github.com/emn178/js-sha256"
    },
    {
        name:"mdui",
        url:"https://github.com/zdhxiong/mdui"
    },
    {
        name:"music-metadata",
        url:"https://github.com/Borewit/music-metadata"
    },
    {
        name:"ffmpeg",
        url:"https://github.com/ffmpegwasm/ffmpeg.wasm"
    },
    {
        name:"node-stream-zip",
        url:"https://github.com/antelle/node-stream-zip"
    },
    {
        name:"npm-run-all",
        url:"https://github.com/mysticatea/npm-run-all"
    },
    {
        name:"opus-decoder",
        url:"https://github.com/eshaz/wasm-audio-decoders"
    },
    {
        name:"qrcode.react",
        url:"https://github.com/zpao/qrcode.react"
    },
    {
        name:"microfuzz",
        url:"https://github.com/Nozbe/microfuzz"
    },
    {
        name:"randomthing-js",
        url:"https://gitee.com/dreamer365/randomthing"
    },
    {
        name:"react-modal-video",
        url:"https://github.com/appleple/react-modal-video"
    },
    {
        name:"react-photo-view",
        url:"https://github.com/MinJieLiu/react-photo-view"
    },
    {
        name:"react-virtuoso",
        url:"https://github.com/petyosi/react-virtuoso"
    },
    {
        name:"speaker",
        url:"https://github.com/TooTallNate/node-speaker"
    },
    {
        name:"uuid",
        url:"https://github.com/uuidjs/uuid"
    },
    {
        name:"tailwindcss",
        url:"https://github.com/tailwindlabs/tailwindcss"
    },
    {
        name:"tailwind-merge",
        url:"https://github.com/dcastil/tailwind-merge"
    },
    {
        name:"use-async-effect",
        url:"https://github.com/rauldeheer/use-async-effect"
    },
    {
        name:"windows-notification-state",
        url:"https://github.com/felixrieseberg/windows-notification-state"
    },
    {
        name:"node-forge",
        url:"https://github.com/digitalbazaar/forge"
    }
] as const;