export default {
    deviceId:"null",
    hasOAuthCredentials:false,
    boundDeviceId:null,
    boundDeviceKey:null,
    heartBeatDelay:"MEDIUM",
    logLevel:"INFO",
    deleteTransmitConflictFile:false,
    enableContentProtection:false,
    autoCheckUpdate:true,
    windowAlwaysOnTop:false,
    enableFileContextMenu:true,
    additionalUnicast:false,
    windowOpacity:100,
    "internal:lastConnectionAddress":"",
    "internal:lastConnectionName":"",
    //绑定设备地址
    "internal:boundDeviceAddress":"",
}