export default{
    //保护通知转发页
    protectNotificationForwardPage:false,
    //保护方式
    protectMethod:"none",
    //通知转发总开关
    enableNotificationForward:true,
    //锁屏时推送通知
    pushNotificationOnLockedScreen:false,
    //全屏时推送通知
    pushNotificationOnFullScreen:true,
    //默认推送模式
    defaultNotificationShowMode:"all",
    //通知转发记录
    enableNotificationLog:true,
    //电池满电提醒
    enableBatteryFullNotification:false,
    //Doze模式提醒
    enableDozeModeChangeNotification:false,
    //解锁屏幕时提示通知数量 只在关闭pushNotificationOnLockedScreen时才有效
    showBlockedNotificationCountOnUnlockScreen:true,
    //手机解锁时不推送通知
    blockNotificationOnDeviceUnlock:false,
    //文件同步开关
    enableFileSync:false,
    //文件同步监听目录
    fileSyncTargetDirectory:[],
    //锁屏时同步锁定通知转发页
    protectNotificationForwardPageOnLockedScreen:false,
}