// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/connect-phone": {
    params: {};
  };
  "/home": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/connect-phone" | "/home";
  };
  "pages/ConnectPhone/ConnectPhone.tsx": {
    id: "pages/ConnectPhone/ConnectPhone";
    page: "/connect-phone";
  };
  "pages/Home/Home.tsx": {
    id: "pages/Home/Home";
    page: "/home";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "pages/ConnectPhone/ConnectPhone": typeof import("./app/pages/ConnectPhone/ConnectPhone.tsx");
  "pages/Home/Home": typeof import("./app/pages/Home/Home.tsx");
};