//修改自:https://www.npmjs.com/package/android-versions
export const AndroidVersions: { [key: number]: AndroidVersionData } = {
    1: { semver: "1.0", name: "1" },
    2: { semver: "1.1", name: "2" },
    3: { semver: "1.5", name: "Cupcake" },
    4: { semver: "1.6", name: "Donut" },
    5: { semver: "2.0", name: "Eclair" },
    6: { semver: "2.0.1", name: "Eclair" },
    7: { semver: "2.1", name: "Eclair" },
    8: { semver: "2.2", name: "Froyo" },
    9: { semver: "2.3", name: "Gingerbread" },
    10: { semver: "2.3.7", name: "Gingerbread" },
    11: { semver: "3.0", name: "Honeycomb" },
    12: { semver: "3.1", name: "Honeycomb" },
    13: { semver: "3.2", name: "Honeycomb" },
    14: { semver: "4.0.1", name: "IceCreamSandwich" },
    15: { semver: "4.0.3", name: "IceCreamSandwich" },
    16: { semver: "4.1", name: "Jellybean" },
    17: { semver: "4.2", name: "Jellybean" },
    18: { semver: "4.3", name: "Jellybean" },
    19: { semver: "4.4", name: "KitKat" },
    20: { semver: "4.4", name: "KitKat Watch" },
    21: { semver: "5.0", name: "Lollipop" },
    22: { semver: "5.1", name: "Lollipop" },
    23: { semver: "6.0", name: "Marshmallow" },
    24: { semver: "7.0", name: "Nougat" },
    25: { semver: "7.1", name: "Nougat" },
    26: { semver: "8.0.0", name: "Oreo" },
    27: { semver: "8.1.0", name: "Oreo" },
    28: { semver: "9", name: "Pie" },
    29: { semver: "10", name: "Q" },
    30: { semver: "11", name: "R" },
    31: { semver: "12", name: "S" },
    32: { semver: "12L", name: "S_V2" },
    33: { semver: "13", name: "Tiramisu" },
    34: { semver: "14", name: "UpsideDownCake" },
    35: { semver: "15", name: "VanillaIceCream" },
    36: { semver: "16", name: "Baklava" },
    37: { semver: "17", name: "CinnamonBun" },
}
export type AndroidVersionData={ semver: string, name: string }